// <auto-generated />
using System;
using Credo.BlobStorage.Migrator.Data.Migration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Credo.BlobStorage.Migrator.Data.Migration.Migrations;

[DbContext(typeof(MigrationDbContext))]
partial class MigrationDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "9.0.0")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("Credo.BlobStorage.Migrator.Data.Migration.MigrationLogEntry", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                b.Property<string>("ClaimedContentType")
                    .HasMaxLength(50)
                    .HasColumnType("character varying(50)");

                b.Property<DateTime>("CreatedAtUtc")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("timestamp with time zone")
                    .HasDefaultValueSql("NOW()");

                b.Property<string>("DetectedContentType")
                    .HasMaxLength(255)
                    .HasColumnType("character varying(255)");

                b.Property<string>("ErrorMessage")
                    .HasMaxLength(2000)
                    .HasColumnType("character varying(2000)");

                b.Property<string>("OriginalExtension")
                    .HasMaxLength(10)
                    .HasColumnType("character varying(10)");

                b.Property<string>("OriginalFilename")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)");

                b.Property<DateTime?>("ProcessedAtUtc")
                    .HasColumnType("timestamp with time zone");

                b.Property<int>("RetryCount")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasDefaultValue(0);

                b.Property<long>("SourceDocumentId")
                    .HasColumnType("bigint");

                b.Property<int>("SourceFileSize")
                    .HasColumnType("integer");

                b.Property<DateTime>("SourceRecordDate")
                    .HasColumnType("timestamp with time zone");

                b.Property<int>("SourceYear")
                    .HasColumnType("integer");

                b.Property<int>("Status")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasDefaultValue(0);

                b.Property<string>("TargetBucket")
                    .HasMaxLength(63)
                    .HasColumnType("character varying(63)");

                b.Property<string>("TargetDocId")
                    .HasMaxLength(50)
                    .HasColumnType("character varying(50)");

                b.Property<string>("TargetFilename")
                    .HasMaxLength(1024)
                    .HasColumnType("character varying(1024)");

                b.Property<string>("TargetSha256")
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)");

                b.HasKey("Id");

                b.HasIndex("Status")
                    .HasDatabaseName("IX_MigrationLog_Status");

                b.HasIndex("SourceYear", "SourceDocumentId")
                    .IsUnique()
                    .HasDatabaseName("UQ_MigrationLog_SourceYear_SourceDocumentId");

                b.ToTable("MigrationLog", (string)null);
            });
#pragma warning restore 612, 618
    }
}
